### ISSUE TITLE
Mejorar ejemplos de consultas sql con ORMs

### ISSUE THREAD

**Issue by lucasdc6** [Proyecto-de-Software/flask-template#11]
Se tienen que agregar algunos ejemplos de consultas un poco más manuales con los distintos ORMs

**Comment by fedeotaran** [comment]
@lucasdc6 mas que nada con Pony que medan dudas para esto. En SQLAchemy se que se puede.

**Comment by matiaspagano** [comment]
En https://docs.ponyorm.org/queries.html#using-raw-sql está lo de pony. 
Algo como: 
`Product.select_by_sql("SELECT * FROM Products")`

**Comment by fedeotaran** [comment]
Genial, deberíamos tener un lugar donde tener esta data disponible para ayuda. Un estilo de solucion a preguntas comunes.

**Comment by matiaspagano** [comment]
un FAQ

**Comment by fedeotaran** [comment]
Tal vez podemos hacer una sección aca para esto

https://github.com/Proyecto-de-Software/docs

**Comment by lucasdc6** [comment]
Me gusta la idea. Después me puedo poner a escribir algunas cosas.

**Comment by fedeotaran** [comment]
Cerramos este issue por inactividad. Aunque es una buena idea la de agregar un FAQ 😏
